[package]
name = "nxp-key-diversifier-2tdea-av2"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = [ "lib" ]

[dependencies]
des = "0.8"
cbc = "0.1"
bitvec = "1"

[dev-dependencies]
criterion = "0.*"

[[bench]]
name = "bench_diversifier"
harness = false